(function(g){var f=window.AmazonUIPageJS||window.P,q=f._namespace||f.attributeErrors,t=q?q("AmazonSafeFrameHostJavaScript",""):f;t.guardFatal?t.guardFatal(g)(t,window):t.execute(function(){g(t,window)})})(function(g,f,q){g.declare("amzn-safe-frame-client-binaries",{"safeFrameContents.html":"https://images-na.ssl-images-amazon.com/images/G/01/AUIClients/AmazonSafeFrameClientJavaScript.90d6825c4f371c62387bf69ac85d50caa4e2ef1f._CB437502652_.html"});"use strict";(function(){function t(a,b,c){return Math.min(0<
a?c-a:0<b?Math.min(b,c):0,b-a)}function A(a,b,c,e){e=Math.pow(10,e);return Math.round(Math.min(c,Math.max(b,a))*e)/e}function Y(){var a=["hidden","webkitHidden","mozHidden","msHidden","oHidden"],b=a.length,c;for(c=0;c<b;c++)if(a[c]in document)return a[c]}function F(a){return"function"===typeof a}function G(){if(l){if(null!==document.body.getAttribute("abp")||null===l.offsetParent||0===l.offsetHeight||0===l.offsetLeft||0===l.offsetTop||0===l.offsetWidth||0===l.clientHeight||0===l.clientWidth)return!0;
if(f.getComputedStyle!==q){var a=f.getComputedStyle(l,null);if(a&&("none"===a.getPropertyValue("display")||"hidden"===a.getPropertyValue("visibility")))return!0}}return!1}function Z(){l=document.createElement("div");l.className="pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links";l.style.cssText="width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -1000px !important;";document.body.appendChild(l);var a=
0,b=G();b||(H=f.setInterval(function(){a++;if((b=G())||6<=a)f.clearInterval(H),l&&(document.body.removeChild(l),l=q),(I=b)&&J.run()},150))}function p(a){a=d.FRAME_BY_ID_SELECTOR.replace("{frameId}",a);return document.querySelector(a)}function K(a){g.when("amzn-safe-frame-client-binaries").execute("amzn-safe-frame-apply-polyfills",function(b){var c;if(c=!a.getAttribute(d.SRC_ATTR_NAME))(c="true"===a.getAttribute(d.USE_SRCDOC_FALLBACK_ATTR_NAME))||(c=aa&&(!!a.getAttribute(d.SRCDOC_ATTR_NAME)||!!a.getAttribute(d.SANDBOX_ATTR_NAME)));
c&&(c=a.getAttribute(d.FRAME_ID_ATTR),(b=(b=b&&b[d.SAFEFRAME_VIEW_NAME])?b+"?safeFrameId\x3d"+c:q)&&a.setAttribute(d.SRC_ATTR_NAME,b))})}function L(a,b){if(b){var c=f.uet,e=a&&a.getAttribute&&a.getAttribute(d.METRICS_SCOPE_ATTR);c&&e&&c("x1",e,{wb:1},b)}b=a&&a.getAttribute&&a.getAttribute(d.DATA_SRCDOC_ATTR_NAME);c=a&&a.getAttribute&&a.getAttribute(d.SRCDOC_ATTR_NAME);b&&!c&&(a[d.SRCDOC_ATTR_NAME]=b,K(a))}function ba(a){return a&&a.getAttribute&&(a=a.getAttribute(d.CAPABILITIES_ATTR_NAME))?a.trim().split(ca).filter(function(a){return M.hasOwnProperty(a)}).reduce(function(a,
c){a[M[c]]=!0;return a},{}):{}}function da(a,b){return!0===ba(a)[b]}function N(a,b,c,e){a.addEventListener?a.addEventListener(b,c,!0===e):a.attachEvent&&a.attachEvent("on"+b,c)}function m(a,b){a&&a.contentWindow&&a.contentWindow.postMessage&&a.contentWindow.postMessage(JSON.stringify(b),"*")}function B(a){h.eachFrame(function(b,c){m(c,a)})}function r(a,b){!0===ea[a]&&(C[a]=b);B({action:"TRIGGER",eventName:a,eventData:b})}function O(a){m(a,{action:"REGISTERED",geom:x.geom(a),isVisible:D.isPageVisible(),
hasAdBlocker:y.hasAdBlocker(),completedEventData:C})}function u(a,b,c){g.when("A").execute(function(e){e&&e.trigger(a,b,c)})}function z(a,b,c){g.when("A").execute(function(e){c&&(b=e.throttle(b,c));e.on(a,b)})}function fa(a,b,c,e){da(a,d.CAPABILITIES.AJAX)?g.when("A").execute(function(d){d.ajax(b,{accepts:e.accepts,cache:e.cache,contentType:e.contentType,method:e.method,params:e.params,paramsFormat:e.paramsFormat,timeout:e.timeout,success:function(b,e){m(a,{action:"AJAX_SUCCESS",requestId:c,response:b,
status:e})},error:function(b,e,d){m(a,{action:"AJAX_ERROR",requestId:c,status:e,error:d})},abort:function(){m(a,{action:"AJAX_ABORT",requestId:c})},chunk:function(b){m(a,{action:"AJAX_CHUNK",requestId:c,chunk:b})}})}):m(a,{action:"AJAX_ERROR",requestId:c,status:"403 Forbidden",error:"Frame missing capability: "+d.CAPABILITIES.AJAX})}var d={ADDITIONAL_ATTRIBUTION_ATTR:"data-additional-attribution",ATTRIBUTION_ATTR:"data-frame-attribution",ATTRIBUTION_SEPARATOR:":",AUTO_LOAD_ATTR_NAME:"data-auto-load",
CAPABILITIES_ATTR_NAME:"data-capabilities",DATA_SRCDOC_ATTR_NAME:"data-srcdoc",FRAME_BY_ID_SELECTOR:'.amzn-safe-frame[data-frame-id\x3d"{frameId}"]',FRAME_CONTAINER_SELECTOR:".amzn-safe-frame-container",FRAME_FOOTER_SELECTOR:".amzn-safe-frame-footer",FRAME_ID_ATTR:"data-frame-id",FRAME_SELECTOR:".amzn-safe-frame",FRAME_SIZING_SELECTOR:".amzn-safe-frame-sizing",HEIGHT_ATTR:"height",HIDDEN_CLASS:"aok-hidden",HOST_METRICS_SCOPE:"amznSafeFrameHost",IFRAME_ELEM_NAME:"iframe",METRICS_SCOPE_ATTR:"data-metrics-scope",
SAFEFRAME_VIEW_NAME:"safeFrameContents.html",SANDBOX_ATTR_NAME:"sandbox",SRC_ATTR_NAME:"src",SRCDOC_ATTR_NAME:"srcdoc",USE_SRCDOC_FALLBACK_ATTR_NAME:"data-use-srcdoc-fallback",WIDTH_ATTR:"width",CAPABILITIES:{AUI:"AUI",AJAX:"AJAX"},EVENTS:{COLLAPSE:"amzn-safe-frame-event:collapse",ERROR:"amzn-safe-frame-event:error",SET_HEIGHT:"amzn-safe-frame-event:set-height",SET_WIDTH:"amzn-safe-frame-event:set-width",SHOW_FOOTER:"amzn-safe-frame-event:show-footer"}},x={geom:function(a){var b=document.documentElement,
c=f.screenTop||f.screenY,e=f.screenLeft||f.screenX,d=f.innerWidth||b.clientWidth,b=f.innerHeight||b.clientHeight,c={t:c,l:e,w:d,h:b,b:c+b,r:e+d,sx:f.scrollX||f.pageXOffset||0,sy:f.scrollY||f.pageYOffset||0},g=e=void 0,h=void 0;try{var k=a.getBoundingClientRect();k.height=k.height||k.bottom-k.top;k.width=k.width||k.right-k.left;var k=h=k,l=t(k.top,k.bottom,b),m=t(k.left,k.right,d),n=l*m,p=k.height*Math.min(k.width,d),e={t:k.top,l:k.left,r:k.right,b:k.bottom,w:k.width,h:k.height,z:+f.getComputedStyle(a,
null).zIndex,xiv:A(m/k.width,0,1,2),yiv:A(l/k.height,0,1,2),iv:A(n/p,0,1,2)},q=document.body,r=document.documentElement,g={t:h.top,l:h.left,r:d-h.right,b:b-h.bottom,xs:Math.max(q.scrollWidth,r.scrollWidth)>d?1:0,yx:Math.max(q.scrollHeight,r.scrollHeight)>b?1:0}}catch(u){g=e=null}return{win:c,self:e,exp:g}}},D={isPageVisible:function(){var a=Y();return a?function(){return!document[a]}:function(){return!0}}()},n={isFunction:F,createHandlerList:function(){var a={},b={};return{add:function(c,e){F(c)&&
(e=e||"___DEFAULT___",!0===b[e]?g.now().execute(c):(a[e]=a[e]||[],a[e].push(c)))},run:function(c){c=c||"___DEFAULT___";b[c]=!0;c=a[c]||[];for(var e=c.length,d=0;d<e;d++)g.now().execute(c[d])}}}},J=n.createHandlerList(),I=!1,l=void 0,H=void 0,y={init:function(){setTimeout(Z,0)},onAdBlockDetected:function(a){J.add(a)},hasAdBlocker:function(){return I}},P=n.createHandlerList();(function(a,b){var c=f[a];c&&(f[a]=function(){var a;try{a=Array.prototype.slice.call(arguments),b.apply(f,a)}finally{c.apply(f,
a)}})})("uet",function(a){a&&P.run(a)});var E={onUet:function(a,b){P.add(b,a)}},h={getFrame:p,getFrameAttribution:function(a,b){a=(a=p(a))?a.getAttribute(d.ATTRIBUTION_ATTR):void 0;var c=["safeFrame"];a&&c.push(a);b&&c.push(b);return c.join(d.ATTRIBUTION_SEPARATOR)},getAdditionalAttribution:function(a){if(a=p(a))return a.getAttribute(d.ADDITIONAL_ATTRIBUTION_ATTR)},getMetricsScope:function(a){if(a=p(a))return a.getAttribute(d.METRICS_SCOPE_ATTR)},setFrameHeight:function(a,b){if(a=p(a))b=Math.max(+b||
0,0),a.setAttribute(d.HEIGHT_ATTR,b)},setFrameWidth:function(a,b){var c=p(a);b=Math.max(+b||0,0);c&&0<b&&g.when("A").execute(function(a){a.$(c).closest(d.FRAME_CONTAINER_SELECTOR).find(d.FRAME_SIZING_SELECTOR).css(d.WIDTH_ATTR,b+"px")})},collapseFrame:function(a){var b=p(a);b&&g.when("A").execute(function(a){a.$(b).closest(d.FRAME_CONTAINER_SELECTOR).addClass(d.HIDDEN_CLASS)})},showFooter:function(a,b){var c=p(a);c&&g.when("A").execute(function(a){a=a.$(c).closest(d.FRAME_CONTAINER_SELECTOR).find(d.FRAME_FOOTER_SELECTOR);
a.removeClass(d.HIDDEN_CLASS);a.data("eventData",b)})},getContents:function(a){if(a=p(a))return a.getAttribute(d.DATA_SRCDOC_ATTR_NAME)||a.getAttribute(d.SRCDOC_ATTR_NAME)},eachFrame:function(a){for(var b=document.querySelectorAll(d.FRAME_SELECTOR),c=b.length,e,f;c--;)e=b[c],(f=e.getAttribute(d.FRAME_ID_ATTR))&&a(f,e)}},ga={wb:1},ha=n.isFunction,Q=f.ueLogError,v=f.ue&&f.ue.count,R={wb:"ues",bb:"uet",af:"uet",cf:"uet",be:"uet",ld:"uex"},w={sendMetrics:function(a,b,c){var d;d=(d=R.hasOwnProperty(b)?
R[b]:q)&&f[d];(a=h.getFrameAttribution(a,c))&&ha(d)&&d(b,a,ga)},logError:function(a,b,c,d){var f=h.getAdditionalAttribution(a);a=h.getFrameAttribution(a,f);b={logLevel:d,attribution:a,message:b};a&&Q&&Q(c||b,c?b:null)},count:function(a,b,c){a=h.getFrameAttribution(a,b);v&&a&&v(a,+c||1)},incrementCount:function(a,b,c){a=h.getFrameAttribution(a,b);c=+c||1;v&&a&&v(a,(v(a)||0)+c)}},aa=!(d.SRCDOC_ATTR_NAME in document.createElement(d.IFRAME_ELEM_NAME)),ca=/\s*,\s*/g,M=Object.keys(d.CAPABILITIES).reduce(function(a,
b){a[d.CAPABILITIES[b]]=b;return a},{}),ea={atf:!0,cf:!0,load:!0},C={},n=function(){},S=f.uet||n,T=f.uex||n,U=f.ue&&f.ue.count||n,V={},W={};S("bb",d.HOST_METRICS_SCOPE,{wb:1});var X={REGISTER:function(a,b,c,d){O(b);!0!==V[c]&&(V[c]=!0,(b=h.getMetricsScope(c))&&S("cf",b,{wb:1},a.timestamp||d))},SEND_METRICS:function(a,b,c){w.sendMetrics(c,a.metric,a.scope)},LOG_ERROR:function(a,b,c){(b=a.message)&&14<b.length&&"window.onerror"===b.substring(0,14)&&(b=U("SafeFrameUncaughtJSError")||0,U("SafeFrameUncaughtJSError",
b+1));w.logError(c,a.message,a.exception,a.logLevel);u(d.EVENTS.ERROR,c,a)},COUNT_METRIC:function(a,b,c){w.count(c,a.counterName,a.value)},INCREMENT_METRIC:function(a,b,c){w.incrementCount(c,a.counterName,a.value)},SET_HEIGHT:function(a,b,c){h.setFrameHeight(c,a.value);u(d.EVENTS.SET_HEIGHT,c,a)},SET_WIDTH:function(a,b,c){h.setFrameWidth(c,a.value);u(d.EVENTS.SET_WIDTH,c,a)},COLLAPSE:function(a,b,c){h.collapseFrame(c);u(d.EVENTS.COLLAPSE,c,a)},SHOW_FOOTER:function(a,b,c){h.showFooter(c,a);u(d.EVENTS.SHOW_FOOTER,
c,a)},GET_CONTENTS:function(a,b,c){m(b,{action:"LOAD_CONTENTS",contents:h.getContents(c)})},CLIENT_READY:function(a,b,c){!0!==W[c]&&(W[c]=!0,(a=h.getMetricsScope(c))&&T("ld",a,{wb:1}))},AJAX:function(a,b,c){fa(b,a.url,a.requestId,a.options)}};N(f,"message",function(a){var b=(new Date).getTime(),c;try{c=JSON.parse(a.data)}catch(d){c={}}if(a=c.frameId){var e=h.getFrame(a);if(e&&X.hasOwnProperty(c.action))X[c.action](c,e,a,b)}},!1);N(document,"visibilitychange",function(){B({action:"VISIBILITY_CHANGE",
isVisible:D.isPageVisible()})},!1);z("resize",function(){h.eachFrame(function(a,b){m(b,{action:"RESIZE",geom:x.geom(b)})})},1E3);z("scroll",function(){h.eachFrame(function(a,b){m(b,{action:"SCROLL",geom:x.geom(b)})})},1E3);z("load",function(){r("atf",{});r("load",{})});z("orientationchange",function(){r("orientationchange",{})});E.onUet("af",function(){r("atf",{})});E.onUet("cf",function(){r("cf",{})});y.onAdBlockDetected(function(){B({action:"AD_BLOCKER_DETECTED"})});n={broadcastEvent:r,initSafeFrameHost:function(){C=
{};h.eachFrame(function(a,b){O(b)});T("ld",d.HOST_METRICS_SCOPE,{wb:1})},reloadFrame:function(a){a.removeAttribute(d.SRCDOC_ATTR_NAME);a.removeAttribute(d.SRC_ATTR_NAME);L(a)},enableAutoResize:function(a){m(a,{action:"ENABLE_AUTO_RESIZE"})},disableAutoResize:function(a){m(a,{action:"DISABLE_AUTO_RESIZE"})}};g.declare("amzn-safe-frame-constants",d);g.declare("amzn-safe-frame-viewability",x);g.declare("amzn-safe-frame-page-visibility",D);g.declare("amzn-safe-frame-ad-block-detect",y);g.declare("amzn-safe-frame-csm-interceptor",
E);g.declare("amzn-safe-frame-manager",h);g.declare("amzn-safe-frame-logging",w);g.declare("amzn-safe-frame-host",n);g.declare("amzn-safe-frame-polyfills",K);g.declare("amzn-safe-frame-auto-loader",function(a,b){"true"===(a&&a.getAttribute&&a.getAttribute(d.AUTO_LOAD_ATTR_NAME))&&L(a,b)});g.when("ready").execute(y.init);n.initSafeFrameHost()})()});
/* ******** */
(function(b){var d=window.AmazonUIPageJS||window.P,e=d._namespace||d.attributeErrors,a=e?e("SearchShoppingPageGridAssets",""):d;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,d,e){b.when("rush-metrics-adapter","jQuery","ready").execute("s-result-grid-metrics",function(a,c){var b;"undefined"!==typeof CSS&&c.isFunction(CSS.supports)&&CSS.supports("grid-auto-flow: dense")?a.setCount("flexigrid:cssGridSupport","s-result-grid-metrics",1):a.setCount("flexigrid:cssGridSupport",
"s-result-grid-metrics",0);c=c(".s-result-list \x3e .s-flex-geom");b=c.filter(":hidden");0<b.length&&a.setCount("flexigrid:resultsHidden","s-result-grid-metrics",b.length);c=c.filter(":visible");0<c.length&&a.setCount("flexigrid:results","s-result-grid-metrics",c.length)})});
/* ******** */
(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("SearchWebFeedbackWidgetAssets",""):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
(function(g){var m=window.AmazonUIPageJS||window.P,y=m._namespace||m.attributeErrors,a=y?y("SearchAssets",""):m;a.guardFatal?a.guardFatal(g)(a,window):a.execute(function(){g(a,window)})})(function(g,m,y){"use strict";g.declare("s-asin-actions",{COUPON_APPLIED:"s-asin-actions:coupon-applied",UPDATE_CART:"s-asin-actions:update-cart"});"use strict";g.when("rush-dispatcher","rush-util").register("s-status-badge-actions",function(a,c){function b(b,c){if(!b)throw Error(c);}var e=a.trigger,h;h={toggleBadges:function(a){b(c.isNotBlank(a),
"asin must be a non-empty string");return"s-badge-actions:toggle-"+a}};return{listeners:h,triggers:{showAll:function(a){b(c.isNotBlank(a),"asin must be a non-empty string");return e(h.toggleBadges(a),{show:!0,check:function(){return!0}})},hideAllExceptType:function(a,f){b(c.isNotBlank(a),"asin must be a non-empty string");b(c.isNotBlank(f),"exceptedType must be a non-empty string");return e(h.toggleBadges(a),{show:!1,check:function(b){return f!==b}})}}}});"use strict";g.when("rush-dispatcher","rush-util").register("s-hidden-content-actions",
function(a,c){function b(b,a){if(!b)throw Error(a);}var e=a.trigger,h;h={markShown:function(a){b(c.isNotBlank(a),"widget must be a non-empty string");return a+":hidden-content:mark-has-shown-content"},hide:function(a){b(c.isNotBlank(a),"widget must be a non-empty string");return a+":hidden-content:hide-content"},slideAndFade:function(a){b(c.isNotBlank(a),"uuid must be a non-empty string");return a+":hidden-content:slide-and-fade-content"},fade:function(a){b(c.isNotBlank(a),"widget must be a non-empty string");
return a+":hidden-content:fade-content"}};return{listeners:h,triggers:{showFirst:function(a,f){b(c.isNotBlank(a),"uuid must be a non-empty string");b(c.isNumber(f),"time must be a number");return e(h.slideAndFade(a),{showingUuid:a,time:f})},markShown:function(a){b(c.isNotBlank(a),"widget must be a non-empty string");return e(h.markShown(a))},show:function(a,f,l){b(c.isNotBlank(a),"widget must be a non-empty string");b(c.isNotBlank(f),"uuid must be a non-empty string");b(c.isNumber(l),"time must be a number");
return e(h.fade(a),{showingUuid:f,time:l})},hide:function(a,f,l){b(c.isNotBlank(a),"widget must be a non-empty string");b(c.isNotBlank(f),"uuid must be a non-empty string");b(c.isNumber(l),"time must be a number");return e(h.hide(a),{showingUuid:f,time:l})}}}});g.declare("s-startup-dom-scan-disabled",!1);g.when("rush-framework","rush-metrics-adapter","s-startup-dom-scan-disabled","ready").execute("s-start-scanner",function(a,c,b){!0!==b&&(c.setTimer("bb","s-startup-component-scan",{wb:1}),c.setTimer("cf",
"s-startup-component-scan",{wb:1}),a.turnOnAutoScanner(),g.declare("s-startup-dom-scan-complete",!0),c.publish("ld","s-startup-component-scan",{wb:1}))});"use strict";g.when("s-clean-url","rush-logger").execute("s-clean-url-replace",function(a,c){try{a&&m.history&&history.replaceState&&history.replaceState(history.state,"cleanUrl",a),g.declare("s-start-application")}catch(b){c.error(b,"Replacing history state with "+a+" failed","s-clean-url-replace")}});"use strict";g.when("A","rush-framework","rush-util",
"a-carousel-framework","a-carousel-constants","s-click-to-functional","s-is-mobile").register("s-searchgrid-carousel",function(a,c,b,e,h,k,f){function l(d){var a=d.getAttr(h.PAGE_NUMBER),b=d.getAttr(h.TOTAL_PAGES),c=d.dom.$container.find(".a-carousel-goto-prevpage");d=d.dom.$container.find(".a-carousel-goto-nextpage");c.toggleClass("aok-hidden",1===a);d.toggleClass("aok-hidden",a===b)}function d(d){!0!==p[d]&&(p[d]=!0,e.onInit(d,function(b){l(b);a.on("a:carousel:"+d+":change:pageNumber",function(d){l(d.carousel)});
a.on("a:carousel:"+d+":change:pageSize",function(d){l(d.carousel)});f||k.recordIfInInitialViewport(b.dom.$container)}))}var r=a.$,p={};c.registerComponent("s-searchgrid-carousel","s-searchgrid-carousel",function(a){var c=r(a.elem()).find(".a-carousel-container"),l=a.prop("name");b.isBlank(l)?a.log.fatal("Search Grid Carousel requires a non-empty name in rush componentProps. Can not initialize carousel."):(d(l),c.hasClass("a-carousel-initialized")||(c.addClass("a-carousel-static"),e.createAll(),e.initializeAll()))})});
"use strict";g.when("A","a-carousel-framework","a-carousel-constants","ready").register("s-carousel-searchgrid",function(a,c,b){function e(d,b,c){for(d=0;-.5<b;)d++,b-=c;0>b&&d--;return a.isFiniteNumber(d)&&0<d?d:1}function h(d){d.onChange(b.PAGE_NUMBER,function(){d.getAttr(b.HIDE_OFF_SCREEN)&&d.dom.$carousel.children("li").css("visibility","")});d.onChange(b.ANIMATING,function(a){var c,h;!a&&d.getAttr(b.HIDE_OFF_SCREEN)&&(c=d.getAttr(b.FIRST_VISIBLE_ITEM)-1,h=c+d.getAttr(b.PAGE_SIZE)-1,d.dom.$carousel.children("li").each(function(d,
a){d=d>=c&&d<=h;l(a).css("visibility",d?"":"hidden")}))})}function k(d,a,c){var l=d.getAttr(b.TOTAL_PAGES),h=d.getAttr(b.PAGE_NUMBER),f=d.getAttr(b.FIRST_VISIBLE_ITEM),k=d.getAttr(b.HIDE_OFF_SCREEN),g=d.dom.$carousel.children("li");a=e(d,a,c);var x=(h-1)*a+1,A,t;d.setAttr(b.PAGE_SIZE,a);h>l?(f=(l-1)*a+1,d.setAttr(b.PAGE_NUMBER,l),d.setAttr(b.FIRST_VISIBLE_ITEM,f)):f!==x&&(l=Math.ceil(f/a),f=(l-1)*a+1,d.setAttr(b.PAGE_NUMBER,l),d.setAttr(b.FIRST_VISIBLE_ITEM,f));A=f-1;t=A+a-1;g.each(function(d,a){a.style.visibility=
!k||d>=A&&d<=t?"":"hidden";a.style.width=c+"px"});return f}function f(d){var a=d.getDimensions().viewport.width,c=d.dom.$carousel.children("li").get(0).getBoundingClientRect(),c=c.width?c.width:c.right-c.left,l=k(d,a,c),f;f=d.dom.$carousel;var h=f.children("li"),e=h.length,g=d.getAttr(b.PAGE_SIZE),x=d.getAttr(b.SET_SIZE),h=h.first().outerWidth(!0),a=g>=x?a:e*h;f.css("width",a+"px");a={carousel:{width:a,outerWidth:f.outerWidth()},items:[]};for(f=0;f<e;f++)a.items.push({width:c,outerWidth:h});d.updateDimensionsCache(a);
d.gotoIndex(l,{animationDuration:0,ignorePause:!0});d.triggerEvent("repaint")}var l=a.$;return{repaint:f,init:function(d){var a=d.getAttr(b.FIRST_VISIBLE_ITEM);d.setAttr(b.MIN_GUTTER,0);d.setAttr("currentGutter",0);f(d);1<a&&(a=Math.ceil(a/d.getAttr(b.PAGE_SIZE)),d.gotoPage(a));h(d)},resize:function(d,a){a.viewport&&a.viewport.width!==y&&f(d)}}});g.when("A","a-carousel-framework","s-carousel-searchgrid").execute("s-register-search-grid-strategy",function(a,c,b){c.registerStrategy("display","searchgrid",
b)});"use strict";g.when("A","a-carousel-constants","a-carousel-utils","a-carousel-transition-slide").register("s-carousel-searchgrid-transition",function(a,c,b,e){function h(b,d,f,h){f?(b.setAttr(c.CURRENTLY_WRAPPING,!0),d.callback=f,d.easingFunction=d.easingFunction||b.getAttr(c.WRAP_EASING),d.animationSpeed=1.3*(a.isFiniteNumber(d.animationSpeed)?d.animationSpeed:b.getAttr(c.ANIMATION_SPEED))):d.callback=h}function k(a,d){(d.animationDuration===y||0<d.animationDuration)&&!d.silent&&a.setAttr(c.ANIMATING,
!0)}function f(a,d){var b=a.getAttr(c.TOTAL_PAGES),f=a.getAttr(c.PAGE_NUMBER),h=a.getAttr(c.PAGE_SIZE),e=a.getAttr(c.SET_SIZE),k=Math.ceil(d/h);d===e-h+1&&k!==f&&(k=b);k!==f&&0<k&&k<=b&&a.setAttr(c.PAGE_NUMBER,k)}b=a.copy(e);b.gotoPage=function(a,d,b){var f=a.getAttr(c.TOTAL_PAGES),h=a.getAttr(c.CIRCULAR),e=a.getAttr(c.PAGE_SIZE),g=a.getAttr(c.SET_SIZE),w=e*(d-1)+1;b=b||{};k(a,b);0<d&&d<=f&&a.setAttr(c.PAGE_NUMBER,d);!h&&1>d?(d=1,b.animationDuration=NaN):!h&&d>f&&(d=f,b.animationDuration=Math.pow(a.getAttr(c.ANIMATION_SPEED),
a.getAttr(c.SPRINGINESS)));d===f&&(w=Math.min(w,g-e+1));this.gotoIndex(a,w,b)};b.gotoIndex=function(a,d,b){var e,g,u,n,w,v;b=b||{};k(a,b);e=a.getAttr(c.CIRCULAR)&&!a.getAttr(c.CURRENTLY_WRAPPING);g=b.callback;u=this;n=null;w=a.getViewportWidth();f(a,d);a.setAttr(c.FIRST_VISIBLE_ITEM,d);1>d?e&&(n=-w,v=function(){g&&g();u.wrapToLast(a)}):d>a.getAttr(c.SET_SIZE)?e&&(n=a.getAttr(c.CURRENT_PIXEL)+w,v=function(){g&&g();u.wrapToFirst(a)}):n=a.getItemOffset(d);h(a,b,v,g);null!==n&&this.gotoPixel(a,n,b)};
return b});g.when("A","a-carousel-framework","s-carousel-searchgrid-transition").execute("s-register-search-grid-transition-strategy",function(a,c,b){c.registerStrategy("transition","s-carousel-searchgrid",b)});"use strict";g.when("A","a-carousel-framework","ready").execute("s-register-search-grid-auto-transition-strategy",function(a,c){c.onInit("feature-card-widget",function(b){function c(){h=!0}var h=!1,k=null,f=b.dom.$container.closest(".s-feature-card").find("ul.a-pagination \x3e li");a.declarative("featurecard-herorotator",
"mouseenter touchstart",function(){null!==k&&clearTimeout(k);h=!1});a.declarative("featurecard-herorotator","mouseleave touchend",function(){k=a.delay(c,4E3)});a.on("a:carousel:feature-card-widget:change:pageNumber",function(a){0<f.length&&(f.eq(a.oldValue-1).removeClass("a-selected"),f.eq(a.newValue-1).addClass("a-selected"))});h=!0;a.interval(function(){h&&b.gotoNextPage()},4E3);b.dom.$container.attr("data-initialized","")})});g.declare("s-disable-ad-feedback",!1);g.when("s-device-env").register("s-device-context",
function(a){a=(a||"").toUpperCase();return{APP:"APP"===a,WEB:"WEB"===a}});g.register("s-device-os",function(){return{IOS:!1,ANDROID:!1,UNRECOGNIZED:!0}});g.declare("s-is-mobile",!1);"use strict";g.when("A","s-disable-ad-feedback","amzn-safe-frame-host","amzn-safe-frame-constants","amzn-safe-frame-manager","s-safe-modal").register("s-ad-feedback-controller",function(a,c,b,e,h,k){function f(a,d){var b,c=d.length;if(a){for(;c--;)if(b=d[c],!a.hasOwnProperty(b))return!1;return!0}return!1}function l(d,
b){var c=0<a.trim(b||"").length;c&&(d.attrs("header",b),d.attrs("popoverLabel",b));d.attrs("hideHeader",!c)}function d(d,b,c,f){return function(h){h.preventDefault();k.whenSingleton(function(h){var e=h.modal,k=h.contentUnavailableText;h.setAttribution(c+":ad-feedback");h.setWidth(f);l(e,d);a.ajax(b,{method:"get",success:function(a){h.setContents(a||k);e.show()},error:function(){h.setContents(k);e.show()}})})}}function r(b,c){var k=h.getFrame(b),l=k&&k.getAttribute(e.ATTRIBUTION_ATTR),r;if(l){c.adPlacementMetaData.feedbackType=
"loomSearch";try{r=JSON.stringify(c)}catch(p){g.log("Error serializing placementData for frameId "+b,"ERROR","s-ad-feedback-controller")}r&&a.ajax("/gp/aq-feedback/lazyLoad/handler/af-link-handler.html",{method:"get",params:{ie:"UTF-8",pl:r},success:function(a){if(f(a,w))if("ok"!==a.status)g.log("Ad Feedback API response had status \x3d\x3d\x3d "+a.status,"ERROR",l);else{var c=a.feedbackLinkText,k=a.feedbackFormModalHeaderText,r=a.feedbackFormModalUrl;a=a.feedbackFormModalWidth;c=u(document.createElement("a")).addClass("s-ad-feedback-link").text(c).attr("href",
"#");c.click(d(k,r,l,a));k=h.getFrame(b);u(k).closest(e.FRAME_CONTAINER_SELECTOR).find(e.FRAME_FOOTER_SELECTOR).empty().append(c)}else g.log("Ad Feedback API response was invalid.","ERROR",l)},error:function(a,d,b){g.log("Error during Ad Feedback API request; status: "+d+", err: "+b,"ERROR",l)},abort:function(){g.log("Ad Feedback API request was aborted.","WARN",l)}})}else g.log("No attribution string present for frameId "+b+" with placementData "+JSON.stringify(c),"FATAL","s-ad-feedback-controller")}
function p(a,d){c||(d=d.data,f(d,n)&&r(a,d))}function q(a,d){c||(d=u(d).closest(e.FRAME_CONTAINER_SELECTOR).find(e.FRAME_FOOTER_SELECTOR),(d=d.data("eventData"))&&p(a,d))}var u=a.$,n=["adPlacementMetaData","adCreativeMetaData"],w=["status","feedbackFormModalUrl","feedbackFormModalHeaderText","feedbackFormModalWidth","feedbackLinkText"];c||(a.on(e.EVENTS.SHOW_FOOTER,p),h.eachFrame(q));return{generateLinkIfFooterVisible:q}});"use strict";g.when("A","s-simple-queue","s-web-application-controller").register("s-delayed-queue-controller",
function(a,c,b){function e(a){l.add(a)}function h(){l.start()}function k(){l.pause()}var f=a.$(m),l=new c;return b.attachController("s-delayed-queue",function(d){d.on(b.ACTIONS.LOAD_SEARCH_PAGE_STARTING,k);d.on(b.ACTIONS.LOAD_SEARCH_PAGE,k);a.on("afterLoad",h);d.on(b.ACTIONS.LOAD_SEARCH_PAGE_COMPLETE,h);f.bind("beforeunload",h);return{add:e,start:h,pause:k}})});"use strict";g.when("A","s-web-application-controller","s-asin-actions","s-status-badge-actions").register("s-add-to-cart-controller",function(a,
c,b,e){function h(b){a.post("/gp/api/cart/1.0/get-cart-count.json",{timeout:5E3,params:{sessionID:b,clientName:"Search"},success:function(a){a&&a.isOK&&a.total?(m.$Nav&&m.$Nav.when("api.setCartCount").run(function(b){b(a.total.numActiveItem)}),g.when("mash").execute("s-add-to-cart-mash-update",function(b){b.cart&&f(b.cart.didUpdate)&&b.cart.didUpdate({newCartQuantity:a.total.numActiveItem})})):g.log("Malformed get-cart-count response for sessionId\x3d"+b,"ERROR","s-add-to-cart-controller")},error:function(){g.log("Failed to retrieve get-cart-count response for sessionId\x3d"+
b,"ERROR","s-add-to-cart-controller")}})}var k={ADD_TO_CART_SUBMIT_START:"s-add-to-cart-controller:submit-start",ADD_TO_CART_SUBMIT_SUCCESS:"s-add-to-cart-controller:submit-success",ADD_TO_CART_SUBMIT_ERROR:"s-add-to-cart-controller:submit-error"},f=a.$.isFunction;return c.attachController("s-add-to-cart-controller",function(c){function d(b){b&&a.post(b)}var f=!1,p=null;a.declarative("s-add-to-cart-controller:make-request","click",function(g){var u,n={},w=g.data.cartType;g.$event.preventDefault();
f||(u=g.$target.closest(".s-atc-form"),a.each(u.serializeArray(),function(a){n[a.name]=a.value}),p=g.data.key,f=!0,c.trigger(k.ADD_TO_CART_SUBMIT_START,{submitterUuid:p}),n.quantity=parseInt(n.quantity,10)||1,n.nextPage="cartitems",a.ajax(g.data.ajaxUrl,{method:"post",params:n,dataType:"json",cache:!1,success:function(v){var x=0,A="PANTRY"===w?n.a:n.ASIN,t=!1;v.items!==y&&a.each(v.items,function(a){a.ASIN===A&&(x+=parseInt(a.quantity,10),t=!0)});x=0!==x?x:n.quantity;f=!1;c.trigger(k.ADD_TO_CART_SUBMIT_SUCCESS,
{submitterUuid:p,asin:A,form:u});c.trigger(b.UPDATE_CART,{asin:A,quantity:x,isTotal:t});e.triggers.hideAllExceptType(A,"in-cart");p=null;"PANTRY"===w&&c.trigger(b.COUPON_APPLIED,{asin:A});h(g.data.sessionId);d(g.data.spUrl);a.trigger("s-add-to-cart-button-component:add-to-cart-success",v)},error:function(){f=!1;p=null;c.trigger(k.ADD_TO_CART_SUBMIT_ERROR);u.submit()}}))});return{ACTIONS:k,isSubmitting:function(){return f},isCurrentAtc:function(a){return a===p}}})});g.when("A","R","s-web-application-controller",
"s-navbar-proxy","rush-util").register("s-navbar-controller",function(a,c,b,e,h){function k(f){var d=a.trim(e.getUrl()||"");h.isBlank(d)||(d=b.SEARCH_PATH+"?"+d,c.to({url:d}),f.preventDefault())}function f(){var a=b.getCurrentKeywords();e.setKeywords(a)}return b.attachController("s-navbar-controller",function(a){e.onSubmit(k);a.on(b.ACTIONS.LOAD_SEARCH_PAGE_STARTING,f);f()})});"use strict";g.when("A","amzn-safe-frame-host","s-web-application-controller").register("s-safe-frame-controller",function(a,
c,b){return b.attachController("s-safe-frame-controller",function(e){e.on(b.ACTIONS.LOAD_SEARCH_PAGE,function(){c.initSafeFrameHost()});e.on(b.ACTIONS.LOAD_SEARCH_PAGE_COMPLETE,function(){c.broadcastEvent("cf",{});c.broadcastEvent("atf",{});c.broadcastEvent("load",{})});g.when("cf").execute("s-safe-frame-controller-cf",function(){c.broadcastEvent("cf",{})});g.when("af").execute("s-safe-frame-controller-atf",function(){c.broadcastEvent("atf",{})});a.on.load(function(){c.broadcastEvent("cf",{});c.broadcastEvent("atf",
{});c.broadcastEvent("load",{})})})});"use strict";g.when("A","nav.updateSearchDropdown","s-web-application-controller").register("s-dropdown-controller",function(a,c,b){var e=["/gp/navigation/ajax/generic.html?ajaxTemplate\x3dsearchDropdown\x26pageType\x3dSearch"];return b.attachController("s-dropdown-controller",function(a){a.on(b.ACTIONS.LOAD_SEARCH_PAGE_COMPLETE,function(){var k,f;if(k=b.getSearchMetadata())k.rescopeNode&&e.push("node\x3d"+k.rescopeNode),k.merchantId&&e.push("merchantId\x3d"+
k.merchantId),k.rid&&e.push("rid\x3d"+k.rid),f=e.join("\x26"),a.ajax(f,{method:"get",success:function(a){c(a)},error:function(b,d,c){a.log.fatal(Error(c),"Ajax to nav endpoint failed: "+d+" - "+f)}})})})});"use strict";g.when("jQuery","R","ready").register("s-filters-controller",function(a,c){a(document).delegate(".s-navigation-checkbox","click",function(b){var e=a(b.currentTarget).closest("a").attr("href");e&&"#"!==e&&(b.preventDefault(),c.to({url:e}))})});"use strict";g.when("R","s-web-application-controller",
"rush-util").register("s-redirect-controller",function(a,c,b){function e(c){c=c&&c.item&&c.item.redirectUrl;b.isNotBlank(c)&&a.replace({url:c})}return c.attachController("s-redirect-controller",function(a){a.on(c.ACTIONS.REDIRECT_READY,e)})});"use strict";g.when("s-web-application-controller").register("s-scroll-controller",function(a){function c(){document.body.scrollTop=document.documentElement.scrollTop=0}return a.attachController("s-scroll-controller",function(b){b.on(a.ACTIONS.LOAD_SEARCH_PAGE,
c)})});g.when("jQuery","s-web-application-controller").register("s-title-and-meta-controller",function(a,c){var b;return c.attachController("s-title-and-meta-controller",function(e){function h(a,b,c){var h=c.find('meta[name\x3d"'+b+'"]');f(a[b])?h.length?h.attr("content",a[b]):c.append('\x3cmeta name\x3d"'+b+'" content\x3d"'+a[b]+'"\x3e'):h.remove()}function k(a,b,c){var h=c.find('link[rel\x3d"'+b+'"]');f(a[b])?h.length?h.attr("href",a[b]):c.append('\x3clink rel\x3d"'+b+'" href\x3d"'+a[b]+'"\x3e'):
h.remove()}var f=e.util.isNotBlank;b={title:function(a,b){document.title=a[b]||""},description:h,keywords:h,canonical:k,prev:k,next:k,noindex:function(a,b,c){var f=c.find('meta[name\x3d"robots"]');!0===a[b]?f.length?f.attr("content","noindex"):c.append('\x3cmeta name\x3d"robots" content\x3d"noindex"\x3e'):f.remove()}};e.on(c.ACTIONS.TITLE_AND_META_READY,function(c){var d=c&&c.item,f=a("head");d&&a.each(b,function(a,b){b(d,a,f)})})})});g.when("rush-framework","s-web-application-controller","s-component-utils").register("s-bottom-slot",
function(a,c,b){var e=c.ACTIONS;a.registerComponent("s-bottom-slot","s-bottom-slot",function(a){a.on(e.LOAD_SEARCH_PAGE,b.remove(a));a.on(e.BOTTOM_SLOT_READY,b.append(a))})});g.when("rush-framework","s-web-application-controller","s-component-utils").register("s-brand-footer-slot",function(a,c,b){var e=c.ACTIONS;a.registerComponent("s-brand-footer-slot","s-brand-footer-slot",function(a){a.on(e.LOAD_SEARCH_PAGE,b.remove(a));a.on(e.BRAND_FOOTER_SLOT_READY,b.append(a))})});g.when("jQuery").register("s-component-utils",
function(a){return{remove:function(c,b){b=b||{};b.hide=!!b.hide;return function(){c.removeChildren(c.elem());b.hide&&a(c.elem()).hide()}},append:function(c){return function(b){b=b&&b.item&&b.item.html||"";c.util.isNotBlank(b)&&(c.append(c.elem(),b),a(c.elem()).show())}},replace:function(c,b){b=b||{};b.empty=!!b.empty;return function(e){e=e&&e.item&&e.item.html||"";c.util.isNotBlank(e)?(c.replaceInnerHTML(c.elem(),e),a(c.elem()).show()):b.empty&&c.removeChildren(c.elem())}}}});g.when("rush-framework",
"s-web-application-controller","s-component-utils").register("s-corrected-search-results",function(a,c,b){var e=c.ACTIONS;a.registerComponent("s-corrected-search-results","s-corrected-search-results",function(a){a.on(e.LOAD_SEARCH_PAGE,b.remove(a));a.on(e.CORRECTED_SEARCH_RESULTS_READY,b.append(a))})});"use strict";g.when("A","rush-framework","s-asin-actions").register("s-coupon-component",function(a,c,b){c.registerComponent("s-coupon-component","s-coupon-component",function(c){var h=c.prop("asin"),
k=a.$(c.elem());c.on(b.COUPON_APPLIED,function(a){a.asin===h&&(k.find(".s-coupon-unclipped").addClass("aok-hidden"),k.find(".s-coupon-clipped").removeClass("aok-hidden"))})})});g.when("rush-framework","s-web-application-controller","s-component-utils").register("s-feedback-slot",function(a,c,b){var e=c.ACTIONS;a.registerComponent("s-feedback-slot","s-feedback-slot",function(a){a.on(e.LOAD_SEARCH_PAGE,b.remove(a));a.on(e.FEEDBACK_SLOT_READY,b.append(a))})});g.when("rush-framework","s-web-application-controller",
"s-component-utils").register("s-filters-panel-view",function(a,c,b){var e=c.ACTIONS;a.registerComponent("s-filters-panel-view","s-filters-panel-view",function(a){a.on(e.LOAD_SEARCH_PAGE,b.remove(a));a.on(e.FILTERS_PANEL_VIEW_READY,b.replace(a))})});g.when("rush-framework","s-web-application-controller","s-component-utils").register("s-fkmr",function(a,c,b){var e=c.ACTIONS;a.registerComponent("s-fkmr","s-fkmr",function(a){a.on(e.LOAD_SEARCH_PAGE,b.remove(a));a.on(e.FKMR_READY,b.append(a))})});g.when("rush-framework",
"s-web-application-controller","s-component-utils").register("s-footer-slot",function(a,c,b){var e=c.ACTIONS;a.registerComponent("s-footer-slot","s-footer-slot",function(a){a.on(e.LOAD_SEARCH_PAGE,b.remove(a));a.on(e.FOOTER_SLOT_READY,b.append(a))})});"use strict";g.when("A","fresh-add-to-cart","s-asin-actions","s-status-badge-actions","rush-util","rush-dispatcher").register("s-fresh-add-to-cart-component",function(a,c,b,e,h,k){function f(a){h.isNotBlank(a)&&(a=d('.s-result-item[data-asin\x3d"'+a+
'"]'),a.find(".s-coupon-unclipped").addClass("aok-hidden"),a.find(".s-coupon-clipped").removeClass("aok-hidden"))}function l(a,c){var f;c=parseInt(c,10);h.isNotBlank(a)&&h.isNumber(c)&&(k.trigger(b.UPDATE_CART,{asin:a,quantity:c,isTotal:!0}),f=d('.s-result-item[data-asin\x3d"'+a+'"]'),f=f.find(".s-in-cart-badge-position"),0<c?(f.removeClass("aok-hidden"),e.triggers.hideAllExceptType(a,"in-cart")):f.addClass("aok-hidden"))}var d=a.$;g.when("ewc.app").execute("s-fresh-ewc-component",function(a){a.on("ewc:cartUpdate:success",
function(a){!a.action||"local-market-delete"!==a.action.name&&"fresh-delete"!==a.action.name||l(a.action.asin,0)})});c.addToFreshCart({success:function(b,c){try{c&&c.isOK&&(d.each(c.items,function(a,b){l(b.ASIN,b.quantity)}),"CLIP_SUCCESSFUL"!==c.couponClipStatus&&"ALREADY_CLIPPED"!==c.couponClipStatus||f(b.$target.closest(".s-result-item").data().asin),b.data&&b.data.loggingUrl&&a.post(b.data.loggingUrl))}catch(h){g.logError(h,"Error caught in freshATC.addToFreshCart success handler.","ERROR","s-fresh-add-to-cart-component")}},
error:function(){g.log("Error reported by freshATC.addToFreshCart error handler.","WARN","s-fresh-add-to-cart-component")}})});g.when("A","jQuery","rush-framework","amzn-safe-frame-viewability","s-add-to-cart-controller","s-hidden-content-actions").register("s-hidden-content",function(a,c,b,e,h,k){var f=h.ACTIONS,l=e.geom;b.registerComponent("s-hidden-content","s-hidden-content",function(b){function h(b){var c;a.show(b);c=b.offset().top;a.hide(b);return c}function e(b){var c;a.show(b);c=b.height();
a.hide(b);return c}function g(a){var b;a.removeClass("aok-hidden");b=a.get(0);b=l(b);b=100*(b&&b.self&&b.self.iv||0)>=C;a.addClass("aok-hidden");return b}function u(){I=!0}function n(){var a=h(z),f=C/100;I?k.triggers.hide(m,B,D):(k.triggers.markShown(m),g(z)?k.triggers.showFirst(B,E):c("html, body").animate({scrollTop:a-J*f},D,function(){c("html, body").stop();k.triggers.showFirst(B,E)}),z.find(".hidden-divider").first().prependTo(z.parents(".s-hidden-content-wrapper").first()),b.trigger(K,{showingUuid:B}))}
function w(b){b.showingUuid!==B&&F&&a.fadeOut(z,b.time,"ease-out",function(){z.addClass("aok-hidden");F=!1;k.triggers.show(m,b.showingUuid,b.time)})}function v(b){b.showingUuid===B&&a.slideDown(z,b.time,"ease-out")}function x(b){b.showingUuid===B&&a.fadeIn(z,b.time,"ease-out",function(){z.removeClass("aok-hidden");F=!0})}function A(a){a.showingUuid!==B&&z.find(".hidden-divider").first().remove()}var t=c(b.elem()),z=t.find(".s-revealable-content"),m=b.prop("widget"),y="#"+m,B=b.prop("uuid"),H=b.prop("event"),
K=m+":remove-dividers",F=!1,I=!1,J,D=parseInt(b.prop("anime-time-fast"),10),E=parseInt(b.prop("anime-time-slow"),10),C=parseInt(b.prop("percent-to-scroll"),10);(function(){return b.util.isBlank(H)?(b.log.error(Error("Missing required component property: event")),!1):b.util.isBlank(m)?(b.log.error(Error("Missing required component property: widget")),!1):b.util.isBlank(B)?(b.log.error(Error("Missing required component property: uuid")),!1):!0})()&&function(){J=e(z);b.util.isNumber(D)||(D=600);b.util.isNumber(E)||
(E=1200);b.util.isNumber(C)||(C=25);b.on(k.listeners.markShown(m),u);b.on(k.listeners.slideAndFade(B),v);b.on(k.listeners.slideAndFade(B),x);b.on(k.listeners.fade(m),x);b.on(k.listeners.hide(m),w);b.on(K,A);if("submit"===H)b.on(f.ADD_TO_CART_SUBMIT_SUCCESS,function(a){a.asin!==b.prop("asin")||!a.form.parents(y).length||F||t.parents(".s-hidden-content-wrapper").first().has(a.form).length||n()})}()})});"use strict";g.when("A","3p-promise","rush-framework","amzn-safe-frame-viewability","s-delayed-queue-controller",
"s-url-parameters","s-web-application-controller").register("s-impression-logger",function(a,c,b,e,h,k,f){function l(b){h.add(function(){a.ajax(b,{method:"get"})})}function d(a,b){this.endpoint=a;this.flushCallback=b;this.items=[];this.timeout=null}function g(){var b=this;this.batches={};a.$(m).bind("beforeunload",function(){a.each(b.batches,function(a){a.flush()})})}var p={leading:!1},q=e.geom,u;d.prototype.add=function(a){var b=this;this.items.push({url:a,params:k.parseQueryString(a)});15<=this.items.length&&
this.flush();this.timeout||(this.timeout=setTimeout(function(){b.flush()},250))};d.prototype.flush=function(){1===this.items.length?l(this.items[0].url):l(this.endpoint+"?params\x3d"+JSON.stringify(a.map(this.items,function(a){return a.params})));clearTimeout(this.timeout);this.timeout=null;this.flushCallback()};g.prototype.log=function(a,b){var c=this,f;b?(f=a.split("?")[0],this.batches[f]||(this.batches[f]=new d(f,function(){delete c.batches[f]})),this.batches[f].add(a)):l(a)};u=new g;b.registerComponent("s-impression-logger",
"s-impression-logger",function(b){function c(){a.off("afterReady",m);a.off("scroll",m);a.off("resize",m);a.off("orientationchange",m);a.each(B,function(a){a&&a()})}function d(){r||c()}var h=b.elem(),e=b.prop("url"),k=b.prop("batchable")||!1,l=b.prop("requiredElementSelector"),g=parseInt(b.prop("percentageShownToFire"),10)||0,r=!1,B=[],m;if(e)return m=a.throttle(function(){var b;if(b=!r)b=q(h),b=100*(b&&b.self&&b.self.iv||0)>=g;b&&(l?(b=a.$(h).find(l),b=0===b.length?!1:!b.is(":hidden")):b=!0);b&&(r=
!0,u.log(e,k),d())},250,p),a.on("afterReady",m),a.on("scroll",m),a.on("resize",m),a.on("orientationchange",m),B.push(b.on(f.ACTIONS.LOAD_SEARCH_PAGE_COMPLETE,m)),{teardown:d}})});"use strict";g.when("A","rush-framework","rush-util","s-asin-actions").register("s-in-cart-badge-component",function(a,c,b,e){function h(a){a=parseInt(a,10);return isNaN(a)?0:a}c.registerComponent("s-in-cart-badge-component","s-in-cart-badge-component",function(c){var f=c.prop("messageTemplate"),l=c.prop("quantityPlaceholder"),
d=a.$(c.elem()),g=c.prop("asin"),p=!0,q=h(c.prop("quantity"));if(b.isBlank(f)||b.isBlank(l))c.log.warn("In Cart Badge component missing data properties for either messageTemplate and/or quantityPlaceholder."),p=!1;c.on(e.UPDATE_CART,function(a){var b,e,v;a&&g===a.asin&&!0===p&&(v=h(a.quantity),!0!==a.isTotal&&0===v?c.log.warn(Error("Invalid In Cart Badge payload quantity.")):(b=d.find(".s-in-cart-badge-position"),e=b.find(".a-badge-text"),q=!0===a.isTotal?v:q+v,e.text(f.replace(l,q)),b.removeClass("aok-hidden")))})})});
g.when("A").register("s-layout-helper",function(a){function c(b){return a.reduce(b,function(a,b){return Math.max(b.offsetTop,a)},0)}var b=a.$;return{normalizeHeights:function(e,h){var k=[];a.each(e,function(f){f=b(f).find(h).get();var e=c(f);a.each(f,function(a){var b={};b.item=a;b.height=e-a.offsetTop;k.push(b)})});a.each(k,function(a){a.item.style.paddingTop=a.height+"px"})},groupElementsByTopValue:function(b){return a.reduce(b,function(a,b){var c=b.offsetTop;a[c]=(a[c]||[]).concat(b);return a},
{})}}});g.when("jQuery","rush-framework","s-web-application-controller","s-component-utils").register("s-pagination",function(a,c,b,e){function h(a){g.when("s-device-context","mash").execute("s-mash-guard",function(b,c){b.APP&&a(c)})}var k=b.ACTIONS;c.registerComponent("s-pagination","s-pagination",function(b){var c=a(b.elem());b.on(k.LOAD_SEARCH_PAGE,e.remove(b),{hide:!0});b.on(k.PAGINATION_LINK_COMPLETE,e.replace(b));h(function(b){c.delegate(".a-pagination \x3e li:first-child a","click",function(c){a.isFunction(b.goBack)&&
(c.stopPropagation(),c.preventDefault(),b.goBack())})})})});"use strict";g.when("A","rush-framework","s-add-to-cart-controller","a-button").register("s-add-to-cart-button-component",function(a,c,b,e){var h=b.ACTIONS;c.registerComponent("s-add-to-cart-button-component","s-add-to-cart-button-component",function(c){var f=c.prop("uuid"),l=a.$(c.elem()),d=e(l.find(".s-atc-button")),g=l.find(".s-atc-spinner");c.on(h.ADD_TO_CART_SUBMIT_START,function(){b.isCurrentAtc(f)&&(g.removeClass("aok-hidden"),d.disable())});
c.on(h.ADD_TO_CART_SUBMIT_SUCCESS,function(){d.enable();g.addClass("aok-hidden")});c.on(h.ADD_TO_CART_SUBMIT_ERROR,function(){d.enable();g.addClass("aok-hidden")});b.isCurrentAtc(f)&&(g.removeClass("aok-hidden"),d.disable())})});"use strict";g.when("A","rush-framework","dynamic-image-loader").register("s-product-image",function(a,c,b){var e=a.$;c.registerComponent("s-product-image","s-product-image",function(a){var c=b.loadChildren([a.elem()]);a.teardown=function(){c&&e.isFunction(c.close)&&c.close()}})});
g.when("A","rush-framework","s-web-application-controller","s-device-context").register("s-result-info-bar",function(a,c,b,e){var h=a.$,k=b.ACTIONS,f={leading:!1};c.registerComponent("s-result-info-bar","s-result-info-bar",function(b){var c=b.elem(),g=h(c),p,q=0,u=!1,n=0,w="up",v=0,x;x=a.throttle(function(){var a=h(document).scrollTop();a>n&&"down"!==w?(v=a,w="down"):a<n&&"up"!==w&&(v=a,w="up");a<q?u&&(p.removeClass("s-mobile-toolbar-offscreen"),u=!1):5<Math.abs(a-v)&&("up"===w?u&&(p.removeClass("s-mobile-toolbar-offscreen"),
u=!1):u||(p.addClass("s-mobile-toolbar-offscreen"),u=!0));n=a},50,f);b.teardown=function(){a.off(a.constants.BROWSER_EVENTS.SCROLL,x)};b.on(k.RESULT_INFO_BAR_READY,function(a){if(a=a&&a.item&&a.item.html)b.replaceInnerHTML(c,a),e.APP&&(p=g.find(".s-mobile-toolbar"),q=p.outerHeight())});e.APP&&(p=g.find(".s-mobile-toolbar"),q=p.outerHeight(),a.on(a.constants.BROWSER_EVENTS.SCROLL,x))})});"use strict";g.when("A","R","rush-framework").register("s-result-sort",function(a,c,b){var e,h=!1;b.registerComponent("s-result-sort",
"s-result-sort",function(b){(function(){e=function(a){var e=b.prop("urls");e&&e[a.value]?c.to({url:e[a.value]}):(a="Invalid result sort option: "+a.value,b.logError(a,Error(a)))};h||(h=!0,a.on("a:dropdown:s-result-sort-select:select",function(a){e.call(y,a)}))})()})});"use strict";g.when("A","a-modal","rush-framework","amzn-safe-frame-manager","amzn-safe-frame-host","amzn-safe-frame-constants").register("s-safe-modal",function(a,c,b,e,h,k){var f=k.EVENTS,l={},d={};b.registerComponent("s-safe-modal",
"s-safe-modal",function(b){var p,q=b.prop("frameId");p=a.$(b.elem());var u=document.createElement("div"),n=b.prop("popoverName"),w=b.prop("html");b=b.prop("contentUnavailableText");var v=e.getFrame(q),x=p.find(k.FRAME_CONTAINER_SELECTOR),m=v.getAttribute(k.DATA_SRCDOC_ATTR_NAME),t=c.create(u,{name:n,header:n,popoverLabel:n,hideHeader:!0,dataStrategy:"preload"});p={frameId:q,frame:v,popoverName:n,triggerElem:u,modal:t,setContents:function(a){a=m.replace(w,a);v.setAttribute(k.DATA_SRCDOC_ATTR_NAME,
a);h.reloadFrame(v)},setWidth:function(b){if(b=parseInt(b,10))e.setFrameWidth(q,b),a.trigger(k.EVENTS.SET_WIDTH,q,{value:b})},setAttribution:function(a){v.setAttribute(k.ATTRIBUTION_ATTR,a)},contentUnavailableText:b};a.$(v).load(function(){h.enableAutoResize(v)});a.on("a:popover:afterHide:"+n,a.debounce(function(){h.disableAutoResize(v)},250,!0));a.on(f.SET_HEIGHT,a.throttle(function(a,b){b.value&&q===a&&t.isActive()&&t.updatePosition()},100));a.on(f.SET_WIDTH,a.throttle(function(a,b){(b=b.value)&&
q===a&&(x.width(b),t.isActive()&&t.updatePosition())},100));a.on(f.COLLAPSE,function(b){q===b&&(t.hide(),a.show(x))});l[n]=p;d[q]=p;"s-safe-modal-singleton"===n&&g.declare("s-safe-modal-singleton",p)});return{getByName:function(a){return l.hasOwnProperty(a)?l[a]:y},getByFrameId:function(a){return d.hasOwnProperty(a)?d[a]:y},whenSingleton:function(a){g.when("s-safe-modal-singleton").execute(a)}}});g.when("jQuery","rush-framework","s-web-application-controller","rush-util").register("s-search-results",
function(a,c,b,e){function h(a,b){if(!a)throw Error(b);}var k=b.ACTIONS;c.registerComponent("s-search-results","s-search-results",function(b){function c(){p.find("\x3e.s-result-item").each(function(a,c){b.remove(c)})}function d(c){var d=!1;p.find("\x3e.s-result-item").each(function(e,h){e=Number(a(h).data("index"));e=isNaN(e)?99:e;if(c.index<e)return b.insertBefore(h,c.html),d=!0,!1});!1===d&&b.append(p[0],c.html)}var g,p;g=a(b.elem());p=g.is(".s-result-list")?g:g.find(".s-result-list");h(p.length,
"Could not find the result list [selector\x3d.s-result-list].");(function(){var a=m.ue,b;a&&a.tag&&(b=0<p.find("\x3e.s-result-item").filter('[data-asin\x3d""]').length,a.tag("hasInlineWidgets:"+(b?"true":"false")))})();b.on(k.LOAD_SEARCH_PAGE,function(){c();g.find(".s-result-list-placeholder").removeClass("aok-hidden")});b.on(k.RESULT_ITEM_READY,function(a){h(e.isObject(a),"payload must be an object");var b=a.item;h(e.isObject(b),"item must be an object");h(e.isNotBlank(b.html),"item.html must be a non-empty string");
h(e.isNumber(b.index),"item.index must be a number");d(a.item)});b.on(k.LOAD_SEARCH_PAGE_COMPLETE,function(){g.find(".s-result-list-placeholder").addClass("aok-hidden")})})});g.when("rush-framework","s-web-application-controller","s-component-utils").register("s-skyscraper-slot",function(a,c,b){var e=c.ACTIONS;a.registerComponent("s-skyscraper-slot","s-skyscraper-slot",function(a){a.on(e.LOAD_SEARCH_PAGE,b.remove(a));a.on(e.SKYSCRAPER_SLOT_READY,b.append(a))})});"use strict";g.when("A","rush-framework",
"rush-util","s-status-badge-actions").register("s-status-badge-component",function(a,c,b,e){c.registerComponent("s-status-badge-component","s-status-badge-component",function(c){function k(a){a.check(c.prop("badgeType"))&&(a.show?f.removeClass("aok-hidden"):f.addClass("aok-hidden"))}var f=a.$(c.elem()),g=c.prop("asin");if(b.isNotBlank(g))c.on(e.listeners.toggleBadges(g),k)})});g.when("rush-framework","s-web-application-controller","s-component-utils").register("s-top-banner",function(a,c,b){var e=
c.ACTIONS;a.registerComponent("s-top-banner","s-top-banner",function(a){a.on(e.LOAD_SEARCH_PAGE,b.remove(a));a.on(e.TOP_BANNER_READY,b.append(a))})});g.when("rush-framework","s-web-application-controller","s-component-utils").register("s-top-slot",function(a,c,b){var e=c.ACTIONS;a.registerComponent("s-top-slot","s-top-slot",function(a){a.on(e.LOAD_SEARCH_PAGE,b.remove(a));a.on(e.TOP_SLOT_READY,b.append(a))})});"use strict";g.when("A","R").execute("s-mobile-link-declarative-action",function(a,c){function b(a){c.to({url:a})}
var e,h=["watch.amazon.","app.primevideo."],k=/[?&]ru=([^&]*)/,f=[["/detail","aiv://aiv/view"],["/watch","aiv://aiv/play"],["/home","aiv://aiv/home"]],l=!!navigator.platform.match(/iPhone|iPod|iPad/);e=b;g.when("mash","rush-logger").execute("s-mobile-link-mash-launchIntentURL",function(a,c){function g(b){a.openInExternalBrowser({url:b,failCallback:function(a){c.error(a,"MASH Open in external browser for "+b+" failed","s-mobile-link")}})}function q(a){var b=new XMLHttpRequest;b.onreadystatechange=
function(){};b.open("GET",a,!0);b.send()}function u(a){var b;if(!a.includes("/gp/video/ssoredirect"))return a;a.startsWith("http://")||a.startsWith("https://")?q(a):(b=m.location,q(b.protocol+"//"+b.host+"/"+a));return(b=k.exec(a))?decodeURIComponent(b[1]):a}function n(a){var b,c,d;for(c=0;c<h.length;c+=1)for(d=0;d<f.length;d+=1)b="https://"+h[c]+"[^/]+"+f[d][0],a=a.replace(new RegExp(b),f[d][1]);return a}e=function(c,f){var e;"true"===f?(c=e=u(c),l&&(c=n(c)),a.launchIntentURL({url:c,failCallback:function(){g(e)}})):
b(c)}});a.declarative("s-link","click",function(a){a.$event.stopPropagation();a.$event.preventDefault();a.data&&a.data.url&&e(a.data.url,a.data.isIntentURL)})});"use strict";g.when("A","jQuery","ready").execute("s-filters-declarative-action",function(a,c){a.declarative("s-nav-ref-image-layout-hover","mouseenter mouseleave",function(a){var e=a.data,h=c(":first-child",a.$currentTarget),k=null,f=null;"mouseenter"===a.type?(k=e.hoverOffsetX,f=e.hoverOffsetY):"mouseleave"===a.type&&(k=e.offsetX,f=e.offsetY);
null!==k&&h.css("background-position",[k,"px ",f,"px"].join(""))})});"use strict";g.when("A","R","s-url-parameters","s-clean-url","GLUXWidget","s-glux-widget-refresh").register("s-glux-widget-refresh-page",function(a,c,b){function e(a){var c=b.parseQueryString(a),f=parseInt(b.getParamValue(c,"refresh"),10);f||(f=0);b.setParamValue(c,"ref","glow_cls");b.removeParamValue(c,"page");b.removeParamValue(c,"spIA");b.setParamValue(c,"refresh",f+1);return a.replace(/[?](.*)/i,"?"+b.paramsToString(c,!0))}a.on("packard:glow:destinationChangeAll",
function(){var a=e(m.location.href);c.to({url:a})});return{replaceUrl:e}});g.when("jQuery").register("s-viewport-utils",function(a){return{inInitialViewport:function(c){var b,e,h;b=!1;var k=document.documentElement,f=document.body;e=m.scrollY||m.pageYOffset||k.scrollTop||f.scrollTop;h=m.scrollX||m.pageXOffset||k.scrollLeft||f.scrollLeft;var g=k.clientHeight,d=k.clientWidth,r=k.clientTop||f.clientTop||0,k=k.clientLeft||f.clientLeft||0;c=a(c);c[0].parentNode&&1<c.height()&&1<c.width()&&(b=c[0].getBoundingClientRect(),
e=b.top+e-r,h=b.left+h-k,b=e<=g&&h<=d);return b}}});"use strict";g.now().execute("s-declare-aspect-ratio-image-initializer",function(){function a(a){h(a,(h(a)||0)+1)}var c=0,b=0,e=0,h=m.ue&&m.ue.count||function(){};(function(){var a=document.createElement("div");return!!a.classList&&(a.closest||a.matches||a.webkitMatchesSelector||a.msMatchesSelector)})()&&(h("ImageAspectWide",0),h("ImageAspectTall",0),h("ImageAspectSquare",0),h("AverageNaturalImagePixels",0),h("AverageDisplayImagePixels",0),g.declare("s-aspect-ratio-image-initializer",
function(g){var f;if(f=g)a:if(f=g,f.closest)f=f.closest(".s-aspect-ratio-image-container");else{do{f.matches=f.matches||f.webkitMatchesSelector||f.msMatchesSelector;if(f.matches(".s-aspect-ratio-image-container"))break a;f=f.parentElement||f.parentNode}while(null!==f&&1===f.nodeType);f=null}var l=f;f=g&&g.naturalWidth;var d=g&&g.naturalHeight;l&&f&&d&&(l.classList.remove("s-source-ratio-wide"),l.classList.remove("s-source-ratio-tall"),l.classList.remove("s-source-ratio-square"),f===d?(l.classList.add("s-source-ratio-square"),
g.style.width="100%",g.style.height="100%",a("ImageAspectSquare")):f>d?(l.classList.add("s-source-ratio-wide"),g.style.width="100%",a("ImageAspectWide")):(l.classList.add("s-source-ratio-tall"),g.style.height="100%",a("ImageAspectTall")),l=g.scrollWidth,g=g.scrollHeight,c+=f*d,b+=l*g,e++,h("AverageNaturalImagePixels",Math.round(c/e)),h("AverageDisplayImagePixels",Math.round(b/e)))}))});g.when("s-viewport-utils").register("s-click-to-functional",function(a){return{recordIfInInitialViewport:function(c){var b=
new Date;a.inInitialViewport(c)&&m.uet&&m.uet("fn",y,y,b)},record:function(){var a=new Date;m.uet&&m.uet("fn",y,y,a)}}});g.when("A","search-js-autocomplete","s-web-application-controller","s-url-parameters").register("s-navbar-proxy",function(a,c,b,e){var h=a.$,k=/ref=([\w\-]+)/,f=/\s+/g;return{getUrl:function(){var a,d,f,p,m;try{a=e.parseQueryString(h("#navbar .nav-searchbar").serialize());d=c.searchAlias&&c.searchAlias();f=c.merchant&&c.merchant();var u=b.getSearchMetadata()||{},n=u.ladderMap||
{},w=u.browseLadder,v;p=!d&&c.searchNode&&(v=c.searchNode())?n[v]||"n:"+v:w&&f?w:void 0;var x=(h("#navbar .nav-searchbar").attr("action")||"").match(k);m=x?x[1]:void 0;f&&e.setParamValue(a,"me",f);d&&e.setParamValue(a,"i",d);p&&e.setParamValue(a,"rh",decodeURIComponent(p));m&&e.setParamValue(a,"ref",m);return e.paramsToString(a,!0)}catch(A){g.log(A,"Failed to build a Search URL from the Navbar.","ERROR","s-navbar-proxy")}},setKeywords:function(b){function d(){return a.trim(b||"").replace(f," ")}c.keyword&&
c.keyword(d)},onSubmit:function(a){h.isFunction(a)&&c.submit&&c.submit(a)}}});g.when("s-metadata").register("s-search-metadata",function(a){function c(a){b=a;g.when("mash").execute("s-set-search-context",function(a){a.dispatchEvent({type:"com.amazon.search.mash.searchContext",detail:b})})}var b;c(a);return{get:function(){return b},set:c}});"use strict";g.declare("s-request-status-constants",{REQUESTED:"requested",CACHED:"cached"});"use strict";g.when("A","rush-router-pattern-parser").register("s-url-parameters",
function(a,c){function b(a){var b;if(!g[a])for(b in h)if(h[b].test(a)){g[a]=b;break}return g[a]||a}var e={portalDebug:!0,ref:!0,qid:!0,rrid:!0,pf:!0},h={},g={};(function(){a.state.bind("s-url-parameters",function(b,c){a.each(b,function(a,b){!0===c[b]&&b&&a&&(h[b]=new RegExp("^("+a+")$"))})});a.each(a.state("s-url-parameters")||{},function(a,b){b&&a&&(h[b]=new RegExp("^("+a+")$"))})})();return{getCanonicalParamName:b,canonicalizeParams:function(a,c){var d={},g,h;for(g in a)if(h=b(g),c||!0!==e[h])d[h]=
a[g];return d},getParamValue:function(a,c){var d=a[c],e;if(d)return d;c=b(c);if(d=a[c])return d;for(e in a)if(c===b(e))return a[e]},setParamValue:function(a,c,d){var e;c=b(c);var g=!1;for(e in a)if(c===b(e)){g=!0;e!==c&&delete a[e];a[c]=d;break}g||(a[c]=d)},paramsToString:function(a,c){var d=[],g,h;for(g in a)if(h=b(g),c||!0!==e[h])null===a[g]?d.push(encodeURIComponent(h)):d.push(encodeURIComponent(h)+"\x3d"+encodeURIComponent(a[g]));return d.sort().join("\x26")},parseQueryString:function(a){a=(a||
"").split("?");a=1<a.length?a.slice(1).join("?"):a[0];return c.parseQueryString(a)},removeParamValue:function(a,c){var d;c=b(c);for(d in a)if(c===b(d)){d!==c&&delete a[d];delete a[c];break}}}});"use strict";g.when("A","rush-framework","rush-page-transition-metrics","s-web-data-store","s-url-parameters","rush-util","rush-metrics-adapter","s-search-metadata","s-start-application").register("s-web-application-controller",function(a,c,b,e,h,k,f,l){var d={PAGE:"page",LAYOUT:"lo",REFTAG:"ref",WILDCARD:"wildcard",
KEYWORDS:"k",KEYWORDS_LONG_FORM:"keywords",NODE:"n"},r={BOTTOM_SLOT_READY:"s-web-application-controller:bottomSlotReady",BRAND_FOOTER_SLOT_READY:"s-web-application-controller:brandFooterSlotReady",SKYSCRAPER_SLOT_READY:"s-web-application-controller:skyscraperSlotReady",CORRECTED_SEARCH_RESULTS_READY:"s-web-application-controller:correctedSearchResultsReady",FEEDBACK_SLOT_READY:"s-web-application-controller:feedbackSlotReady",FILTERS_LINK_VIEW_READY:"s-web-application-controller:filtersLinkViewReady",
FILTERS_PANEL_VIEW_READY:"s-web-application-controller:filtersPanelViewReady",FKMR_READY:"s-web-application-controller:fkmrReady",FOOTER_SLOT_READY:"s-web-application-controller:footerSlotReady",LOAD_SEARCH_PAGE:"s-web-application-controller:loadSearchResults",LOAD_SEARCH_PAGE_COMPLETE:"s-web-application-controller:loadSearchResultsComplete",LOAD_SEARCH_PAGE_STARTING:"s-web-application-controller:loadSearchPageStarting",PAGINATION_LINK_COMPLETE:"s-web-application-controller:paginationLinkComplete",
RESULT_INFO_BAR_READY:"s-web-application-controller:resultInfoBarReady",RESULT_ITEM_READY:"s-web-application-controller:resultItemReady",REDIRECT_READY:"s-web-application-controller:redirectReady",SEARCH_METADATA_READY:"s-web-application-controller:searchMetadataReady",SHOPPING_PAGE_NAVIGATION_READY:"s-web-application-controller:shoppingPageNavigationReady",TITLE_AND_META_READY:"s-web-application-controller:titleAndMetaReady",TOP_BANNER_READY:"s-web-application-controller:topBannerReady",TOP_SLOT_READY:"s-web-application-controller:topSlotReady"};
f.setTimer("bb","s-swac",{wb:1});return c.attachApp("search-web-application","s-web-application-controller",function(c){function q(a){var b=h.getCanonicalParamName(d.PAGE);k.setIfEmpty(a,b,"1")}function u(a){a=h.canonicalizeParams(a);q(a);z=a;y=h.paramsToString(z)}function n(){G||(c.trigger(b.EVENTS.BEGIN_RESPONSE),G=!0)}function w(){c.startPageStateDispatcher({paramString:y})}function v(a,b){a=h.canonicalizeParams(a,b);delete a[d.WILDCARD];q(a);return a}function x(){var a=!1;g.now("s-device-context").execute("s-is-app",
function(b){b&&b.APP&&(a=!0)});return a}function A(){var a=!1;g.now("s-device-os").execute("s-resolve-device-os",function(b){b&&b.IOS&&(a=!0)});return a}var t=e(c),z={},y,G=!1;c.on(t.ACTIONS.ITEM_READY,function(a){if(a&&a.paramString===y)switch(n(),a.type){case t.ITEM_TYPES.SEARCH_RESULTS:c.trigger(r.RESULT_ITEM_READY,a);break;case t.ITEM_TYPES.PAGINATION:c.trigger(r.PAGINATION_LINK_COMPLETE,a);break;case t.ITEM_TYPES.CLIENT_SIDE_METRICS_INFO:c.trigger(b.EVENTS.RECEIVED_METRICS_INFO,a.item);break;
case t.ITEM_TYPES.CORRECTED_SEARCH_RESULTS:c.trigger(r.CORRECTED_SEARCH_RESULTS_READY,a);break;case t.ITEM_TYPES.FILTERS_PANEL_VIEW:c.trigger(r.FILTERS_PANEL_VIEW_READY,a);break;case t.ITEM_TYPES.FILTERS_LINK_VIEW:c.trigger(r.FILTERS_LINK_VIEW_READY,a);break;case t.ITEM_TYPES.FKMR:c.trigger(r.FKMR_READY,a);break;case t.ITEM_TYPES.RESULT_INFO_BAR:c.trigger(r.RESULT_INFO_BAR_READY,a);break;case t.ITEM_TYPES.TITLE_AND_META:c.trigger(r.TITLE_AND_META_READY,a);break;case t.ITEM_TYPES.TOP_BANNER:c.trigger(r.TOP_BANNER_READY,
a);break;case t.ITEM_TYPES.TOP_SLOT:c.trigger(r.TOP_SLOT_READY,a);break;case t.ITEM_TYPES.BOTTOM_SLOT:c.trigger(r.BOTTOM_SLOT_READY,a);break;case t.ITEM_TYPES.FOOTER_SLOT:c.trigger(r.FOOTER_SLOT_READY,a);break;case t.ITEM_TYPES.BRAND_FOOTER_SLOT:c.trigger(r.BRAND_FOOTER_SLOT_READY,a);break;case t.ITEM_TYPES.SKYSCRAPER_SLOT:c.trigger(r.SKYSCRAPER_SLOT_READY,a);break;case t.ITEM_TYPES.FEEDBACK_SLOT:c.trigger(r.FEEDBACK_SLOT_READY,a);break;case t.ITEM_TYPES.SEARCH_METADATA:l.set(a&&a.item&&a.item.metadata||
{});c.trigger(r.SEARCH_METADATA_READY,a);break;case t.ITEM_TYPES.SHOPPING_PAGE_NAVIGATION:c.trigger(r.SHOPPING_PAGE_NAVIGATION_READY,a);break;case t.ITEM_TYPES.REDIRECT:c.trigger(r.REDIRECT_READY,a)}});c.on(t.ACTIONS.REQUEST_COMPLETE,function(a){a&&a.paramString===y&&(n(),c.trigger(r.LOAD_SEARCH_PAGE_COMPLETE,a))});c.on(t.ACTIONS.REQUEST_ERROR,function(b){var c=b&&b.attempt||1,d=b&&b.retry;b.paramString===y&&(2>c&&a.$.isFunction(d)?d(!0):(f.incrementCount("s-swac","force-reloads",{wb:1}),m.location.reload(!0)))});
(function(){function e(){var a=!1;g.now("s-startup-dom-scan-complete","s-ajax-enabled").execute(function(b,c){a=!!b&&!!c});return a}function k(d){var l=v(d,!1);if(m){var n=v(z,!1),q;a:{n=a.diff(l,n);for(q in n)if(n.hasOwnProperty(q)&&!0===n[q]){q=!0;break a}q=!1}if(!q)return;(q=!e())||(q=h.getParamValue(l,"i"),n=h.getParamValue(z,"i"),q=q!==n&&!x());if(q)return x()&&!A()&&(u(l),c.trigger(r.LOAD_SEARCH_PAGE,{params:l})),!1;G=!1;c.trigger(b.EVENTS.BEGIN_REQUEST)}f.incrementCount("s-swac","pages",{wb:1});
u(l);c.trigger(r.LOAD_SEARCH_PAGE_STARTING,{isAjax:m});m?(c.trigger(r.LOAD_SEARCH_PAGE,{params:l}),t.request(v(d,!0))):(m=!0,g.when("ready").execute("s-route-handler-load-state",w))}function l(a){var b;b=a.hasOwnProperty(d.KEYWORDS)?a[d.KEYWORDS]:a.hasOwnProperty(d.KEYWORDS_LONG_FORM)?a[d.KEYWORDS_LONG_FORM]:a[d.WILDCARD];a[d.KEYWORDS]=b;delete a[d.KEYWORDS_LONG_FORM];return k(a)}var m=!1;c.addRoute("(/**)/s",k);c.addRoute("(/**)/s(/ref\x3d**)",function(a){a.hasOwnProperty(d.REFTAG)||(a[d.REFTAG]=
a[d.WILDCARD]);return k(a)});c.addRoute("(/**)/s/k\x3d**",l);c.addRoute("(/**)/s/keywords\x3d**",l);c.addRoute("(/**)/s/n\x3d**",function(a){a.hasOwnProperty(d.NODE)||(a[d.NODE]=a[d.WILDCARD]);return k(a)});f.setTimer("cf","s-swac",{wb:1});f.publish("ld","s-swac",{wb:1})})();return{ACTIONS:r,FILTERS_POPOVER_NAME:"filter_view",PARAMS:d,SEARCH_PATH:"/s",getCurrentKeywords:function(){return h.getParamValue(z,d.KEYWORDS)||""},getSearchMetadata:function(){return l.get()}}})});"use strict";g.when("A","s-simple-namespaced-cache",
"s-url-parameters","rush-util","rush-metrics-adapter","s-request-status-constants").register("s-web-data-store",function(a,c,b,e,g,k){function f(a){a=b.canonicalizeParams(a);return b.paramsToString(a)}var l={ITEM_READY:"s-web-data-store:itemReady",REQUEST_ERROR:"s-web-data-store:requestError",REQUEST_COMPLETE:"s-web-data-store:requestComplete"},d={BOTTOM_SLOT:"bottom-slot",BRAND_FOOTER_SLOT:"brand-footer-slot",CLIENT_SIDE_METRICS_INFO:"client-side-metrics-info",CORRECTED_SEARCH_RESULTS:"corrected-search-results",
FEEDBACK_SLOT:"feedback-slot",FILTERS_LINK_VIEW:"filters-link-view",FILTERS_PANEL_VIEW:"filters-panel-view",FKMR:"fewer-keywords-more-results",FOOTER_SLOT:"footer-slot",PAGINATION:"pagination",REDIRECT:"redirect",RESULT_INFO_BAR:"result-info-bar",SEARCH_METADATA:"search-metadata",SEARCH_RESULTS:"search-results",SEARCH_RESULTS_METADATA:"results-metadata",SHOPPING_PAGE_NAVIGATION:"shopping-page-navigation",SKYSCRAPER_SLOT:"skyscraper-slot",TITLE_AND_META:"title-and-meta",TOP_BANNER:"top-banner",TOP_SLOT:"top-slot"},
m=function(){var a={},b;for(b in d)d.hasOwnProperty(b)&&(a[d[b]]=b);return a}();return function(a){function b(c,d){var m=f(c);e!==m&&(e=m,d=d||1,a.ajax("/s/query",{method:"get",params:c,memo:{paramString:m},success:function(){a.trigger(l.REQUEST_COMPLETE,{paramString:m,requestStatus:k.REQUESTED})},error:function(e,f,k){e=["s-web-data-store AJAX request error",f,k,m].join(", ");a.log.error(Error(e),e);g.incrementCount("s-retry-ajax");a.trigger(l.REQUEST_ERROR,{paramString:m,attempt:d,retry:function(){b(c,
d+1)}})}}))}function c(b,d){b=b.substr(5).split(":")[0];var e,f;m.hasOwnProperty(b)&&(e=d.data,d=d.memo&&d.memo.paramString,e&&d&&(f=e.index,b={type:b,item:e,index:f,paramString:d},a.trigger(l.ITEM_READY,b)))}var e;(function(){a.onPrefix("data-",c);a.on(d.CLIENT_SIDE_METRICS_INFO,function(a){c("data-"+d.CLIENT_SIDE_METRICS_INFO,a)})})();return{ACTIONS:l,ITEM_TYPES:d,request:function(a){b(a)}}}});"use strict";g.register("s-simple-namespaced-cache",function(){function a(){this.data={}}a.prototype.get=
function(a,b){b=b||"";if(this.data[b]&&this.data[b].hasOwnProperty(a))return this.data[b][a]};a.prototype.put=function(a,b,e){e=e||"";this.data[e]=this.data[e]||{};b===y&&this.data[e].hasOwnProperty(a)?delete this.data[e][a]:this.data[e][a]=b};a.prototype.remove=function(a,b){this.put(a,y,b)};a.prototype.clear=function(){this.data={}};a.prototype.clearNamespace=function(a){delete this.data[a||""]};a.prototype.clearKey=function(a){for(var b in this.data)this.remove(a,b)};return a});"use strict";g.when("A",
"3p-promise").register("s-simple-queue",function(a,c){function b(a){return new c(function(b){b(a())})}function e(){this.items=[];this.running=!1}var g=a.$.isFunction,k=a.$.proxy;e.prototype.add=function(a){if(g(a))this.items.push(a),this.next();else throw Error("s-simple-queue: argument to add() is not a function.");};e.prototype.next=function(){var a,e;return!0===this.running&&0<this.items.length?(a=this.items.shift(),e=k(this.next,this),b(a).then(e,e)):c.resolve()};e.prototype.start=function(){this.running=
!0;return this.next()};e.prototype.pause=function(){this.running=!1};return e})});
/* ******** */
